### ISSUE TITLE
Embedded Logging Conflict 

### ISSUE THREAD

**Issue by monowai** [neo4j/neo4j#2605]
I run Neo4j embedded. Since 1.9 I've excluded the Neo4J qos logging libraries as something in them conflicts with my apps logging configuration.

After upgrading to 2.1.x my app started throwing the stacktrace below.
Re-including your logging library makes the problem below go away but we're back to Neo4J overriding my apps log configuration (see the problem above)

```
Caused by: java.lang.NoClassDefFoundError: org/neo4j/kernel/impl/nioneo/xa/XaCommandWriterFactory
    at org.neo4j.kernel.api.impl.index.IndexWriterFactories$1.create(IndexWriterFactories.java:41)
    at org.neo4j.kernel.api.impl.index.LuceneLabelScanStore.init(LuceneLabelScanStore.java:258)
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:483)
    ... 128 more
Caused by: java.lang.ClassNotFoundException:    
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 131 more
```

These are the exclusions causing the problem in the stacktrace.

```
<dependency>
            <groupId>org.neo4j</groupId>
            <artifactId>neo4j</artifactId>
            <version>${neo4j.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>logback-classic</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>logback-access</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```
